// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGLO1JNsL9kX11pWuZ2sedvAsFFU3DOkY',
    appId: '1:988334755775:web:0ac432f3ffdebda0491b0a',
    messagingSenderId: '988334755775',
    projectId: 'avpromisse',
    authDomain: 'avpromisse.firebaseapp.com',
    storageBucket: 'avpromisse.firebasestorage.app',
    measurementId: 'G-578H5QYM64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXfCWpXIOD5Vw_Dw_R-KLgbsou2RUvKNQ',
    appId: '1:988334755775:android:37773d802d8d29c3491b0a',
    messagingSenderId: '988334755775',
    projectId: 'avpromisse',
    storageBucket: 'avpromisse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZMY-aX5dzGCYTxPuY9eW16p_H4o9Jx4s',
    appId: '1:988334755775:ios:1efcf23b1fb0f77d491b0a',
    messagingSenderId: '988334755775',
    projectId: 'avpromisse',
    storageBucket: 'avpromisse.firebasestorage.app',
    iosBundleId: 'com.avpromisse.agenda',
  );
}
